// Basket
export const PRODUCT_ADDED_TO_BASKET = 'PRODUCT_ADDED_TO_BASKET';
export const PRODUCT_REMOVED_FROM_BASKET = 'PRODUCT_REMOVED_FROM_BASKET';
export const ALL_PRODUCTS_REMOVED_FROM_BASKET =
  'ALL_PRODUCTS_REMOVED_FROM_BASKET';

// Data
export const DATA_LOADED = 'DATA_LOADED';
export const DATA_REQUESTED = 'DATA_REQUESTED';
export const DATA_ERROR = 'DATA_ERROR';
